### ISSUE TITLE
I hope to incorporate Subaru's SNG function on the dragonpilot. Is there any pr for reference?

### ISSUE THREAD

**Issue by sadmenmen** [martinl/openpilot#108]
I hope to incorporate Subaru's SNG function on the dragonpilot. Is there any pr for reference?

**Comment by martinl** [comment]
There is a new sng autoresume PR open https://github.com/commaai/openpilot/pull/28064 that cleans up the current sng implementation in subaru-community. It should be tested and ready for merge in next week.
