### ISSUE TITLE
Subaru FPv2

### ISSUE THREAD

**Issue by martinl** [martinl/openpilot#20]
Initial Subaru FPv2 support is implemented in subaru-PR-test branch (https://github.com/martinl/openpilot/blob/subaru-PR-test/selfdrive/car/fw_versions.py#L62) using ROM ID from OBD Mode 22 queries (22 F1 82)

Some sample FPv2 values gathered from openpilot users for Impreza, Crosstrek, Outback and Forester: https://github.com/martinl/openpilot/blob/subaru-PR-test/selfdrive/car/subaru/values.py#L104

TODO
- Find a solution for currently required 10 second pre-delay for queries when switching on ignition
- Verify if ROM ID is used for checking ECU firmware versions / updates in SSM4

**Comment by kram322** [comment]
Don't know if its needed but this is from my 2018 2.5i Premium Legacy

    carFw = [
      (ecu = engine, fwVersion = "\xb5\"@p\a", address = 2016, subAddress = 0),
      ( ecu = transmission,
        fwVersion = "\xbc\xf2\x00\x81\x00",
        address = 2017,
        subAddress = 0 ),
      ( ecu = fwdRadar,
        fwVersion = "\xf1\x00\x00\x00\x02",
        address = 2000,
        subAddress = 0 ),
      ( ecu = eps,
        fwVersion = "{\xb0\x00\x00",
        address = 1862,
        subAddress = 0 ),
      ( ecu = esp,
        fwVersion = "\x8b\x97D\x00",
        address = 1968,
        subAddress = 0 ),
      ( ecu = fwdCamera,
        fwVersion = "\x00\x00df\x1f@ \n",
        address = 1927,
        subAddress = 0 ) ],
    radarTimeStep = 0.05,
    communityFeature = true,
    steerLimitTimer = 0.4,
    fingerprintSource = can,
    networkLocation = fwdCamera ) )

**Comment by martinl** [comment]
> Don't know if its needed but this is from my 2018 2.5i Premium Legacy

thanks, added the FPv2 to subaru-PR-test

**Comment by martinl** [comment]
There is initial confirmation of FPv2 in the form of two 2018 Foresters which have matching ROM ID-s (except for transmission)

**Comment by martinl** [comment]
And similar confirmation with two 2019 Ascent ROM ID-s

**Comment by martinl** [comment]
PR https://github.com/commaai/openpilot/pull/1878

**Comment by martinl** [comment]
10 second delay after ignition needs to be resolved before upstreaming

**Comment by martinl** [comment]
10 second delay was not needed, merged to upstream
