### ISSUE TITLE
Add Subaru Ascent support

### ISSUE THREAD

**Issue by martinl** [martinl/openpilot#23]
Initial support and tuning values from ndtran in subaru-PR-test, waiting for FPv2 values
- [x] 2019
- [x] 2020

Prerequsites for upstreaming 2020
- [Subaru FPv2](https://github.com/martinl/openpilot/issues/20) (some Ascents fingerprint as Impreza using FPv1)

**Comment by martinl** [comment]
2019 Ascent Limited has different FPv1 than Impreza, upstreamed with https://github.com/commaai/openpilot/pull/1801

**Comment by bbennett80** [comment]
2020 Ascent Touring; FPv2 from useradmin log:

carFw = [
      ( ecu = fwdRadar,
        fwVersion = "\xf1\000\000\000\002",
        address = 2000,
        subAddress = 0 ),
      (ecu = engine, 
	  fwVersion = "\xf1\x82\xd1,\xa0q\a", 
	  address = 2016, 
	  subAddress = 0),
      ( ecu = transmission,
        fwVersion = "\001\xfe\xf8\000\000",
        address = 2017,
        subAddress = 0 ),
      ( ecu = fwdCamera,
        fwVersion = "\xf1\000\xac\004\000",
        address = 1988,
        subAddress = 0 ),
      (ecu = eps, f
	  wVersion = "\x95\xc0\xd0\000", 
	  address = 1862, 
	  subAddress = 0),
      ( ecu = esp,
        fwVersion = "\xa5 \031\002\000",
        address = 1968,
        subAddress = 0 ),
      ( ecu = fwdCamera,
        fwVersion = "\000\000e@\037@ $",
        address = 1927,
        subAddress = 0 ) ],


with HEX conversion and formatting:

  CAR.ASCENT = {
    # Ecu, addr, subaddr: ROM ID
     (Ecu.esp, 0x7b0, None): [
       b'\xa5 \031\002\000',
     ],
     (Ecu.eps, 0x746, None): [
       b'\x95\xc0\xd0\000', 
     ],
     (Ecu.fwdCamera, 0x787, None): [ 
       b'\000\000e@\037@ $',
     ],
     (Ecu.engine, 0x7e0, None):
	b'\xf1\x82\xd1,\xa0q\a', 
     ],
     (Ecu.transmission, 0x7e1, None):
       b'\001\xfe\xf8\000\000',
     ],
    },


2020 Ascent Touring; FPv1 from "Creating Fingerprint 1.0 (deprecated)":
number of messages 64:
fingerprint 2: 8, 64: 8, 65: 8, 72: 8, 73: 8, 280: 8, 281: 8, 290: 8, 312: 8, 313: 8, 314: 8, 315: 8, 316: 8, 326: 8, 544: 8, 545: 8, 546: 8, 552: 8, 554: 8, 557: 8, 576: 8, 577: 8, 722: 8, 801: 8, 802: 8, 805: 8, 808: 8, 811: 8, 816: 8, 826: 8, 837: 8, 838: 8, 839: 8, 842: 8, 912: 8, 915: 8, 940: 8, 1614: 8, 1617: 8, 1632: 8, 1650: 8, 1657: 8, 1658: 8, 1677: 8, 1722: 8, 1743: 8, 1759: 8, 1785: 5, 1786: 5, 1787: 5, 1788: 8, 1862: 8, 1870: 8, 1927: 8, 1935: 8, 1968: 8, 1976: 8, 1988: 8, 1996: 8, 2015: 8, 2016: 8, 2017: 8, 2024: 8, 2025: 8



Please let me know if we need to add anything else.

**Comment by martinl** [comment]
Subaru FPv2 is upstreamed, Ascent 2020 is supported now
