### ISSUE TITLE
ACC disengage during braking

### ISSUE THREAD

**Issue by martinl** [martinl/openpilot#27]
Current state

- [x] Crosstrek 2020 - fix confirmed (increase Brake_Pedal threshold to 1.0 for global models) - using Brake_Status Brake for all global models needs testing
- [x] Outback 2016 - fix confirmed (increase Brake_Pedal threshold to 2.0 for preglobal models)
- [x] Forester 2019 - fix confirmed (fixed using Brake_Status Brake in forester-2019 branch)
- [x] Outback 2020 - fix confirmed(fixed using Brake_Status Brake signal in outback-2020-gen2 branch)
- [x] Crosstrek 2020 Hybrid - fix confirmed (fixed using Brake_Hybrid Brake signal, crosstrek-hybrid-2020-gen2 branch)

Users with 2020 Crosstrek (1will) 2020 Crosstrek Hybrid (dave32) and 2016 Outback Limited 2.5 (aeiro) have reported that openpilot sometimes disengages while stock acc is braking

Drive behind lead car with openpilot engaged, wait for lead car to stop. Openpilot disengages while braking before car is stopped

**Expected behavior**

Openpilot should not disengage

**Device/Version information (please complete the following information):**
 - Device: multiple
 - Dongle ID: 
 - Route: 5cbf0beff26ee650|2020-07-04--23-52-34 (at 271), 31b5813859279160|2020-07-03--08-13-47 (at 1202)
 - Version: subaru-PR-test (e5901b3c95eaef1574a7be9571000b456e99fa0e), crosstrek-2020-hybrid (a4ec6102e794c47ecb6719238ce255790798fc86), crosstrek-2020-fix (438198d7e92cb229067b322172dda7a6ae8f9cb0)
 - Car make/model: Subaru Crosstrek 2020, Subaru Crosstrek 2020 Hybrid, Subaru Outback 2016

**Additional context**

Cabana logs show that car is sending short user brake (Brake_Pedal:Brake_Pedal with value 1 or 2 on can0) message while Eyesight is braking which causes openpilot to send acc disengage message

Crosstrek 2020 (1will)
<img width="390" alt="Screenshot 2020-07-03 at 23 52 58" src="https://user-images.githubusercontent.com/148686/86526646-3ff01e80-be9f-11ea-9e5a-a9bed2c5b606.png">

Outback 2016 (aeiro)
<img width="429" alt="Screenshot 2020-07-05 at 09 11 35" src="https://user-images.githubusercontent.com/148686/86526673-965d5d00-be9f-11ea-8b49-be67ce7873e0.png">

The issue correlates with heavy (2-2.5m/s2) deceleration/braking by stock acc
<img width="431" alt="Screenshot 2020-07-07 at 10 44 09" src="https://user-images.githubusercontent.com/148686/86740065-08b87380-c03f-11ea-8542-d77d7248cb52.png">

**Comment by martinl** [comment]
Pushed an update to crosstrek-2020-fix and crosstrek-2020-hybrid branches to test if increasing brake pressed threshold to 1 in carstate and panda safety fixes the issue

**Comment by martinl** [comment]
Initial fix is confirmed working on Crosstrek 2020 non-hybrid (1will), waiting for feedback from hybrid model testers

**Comment by martinl** [comment]
Crosstrek Hybrid 2020 (Dave32) disengage on braking issue
<img width="423" alt="Screenshot 2020-07-14 at 19 50 00" src="https://user-images.githubusercontent.com/148686/87460497-a4387e00-c615-11ea-968c-748c56517ee6.png">

Brake Pedal vs acceleration
<img width="416" alt="Screenshot 2020-07-14 at 21 47 17" src="https://user-images.githubusercontent.com/148686/87464377-b1f10200-c61b-11ea-8e00-b43a5a51405f.png">

**Comment by martinl** [comment]
The cause for 2020 Crosstrek Hybrid braking issue is different from 2020 Crosstrek ICE and 2016 Outback. 2020 Hybrid driver and eyesight brake signals are combined and we need to find separate driver brake pressed signal to use for openpilot disengage

Eyesight stock drive, braking to stop behind lead car
<img width="425" alt="Screenshot 2020-07-16 at 06 37 37" src="https://user-images.githubusercontent.com/148686/87625321-87459d00-c732-11ea-9d1a-42e4d0dbbda2.png">

**Comment by martinl** [comment]
aeiro tested the preglobal brake threshold fix on preglobal-brake-fix branch for a few weeks with Outback 2016  and confirmed that the issue is fixed

**Comment by martinl** [comment]
Using Brake_Status Brake signal instead of Brake_Pedal is a possible fix for hybrids, needs testing

**Comment by martinl** [comment]
Users reported similar issues with two additional models:
- Outback 2020 - sometimes sends Brake_Pedal = 16 while ES is braking
- Forester 2019 - sometimes sends Brake_Pedal = 16 while ES is braking

<img width="387" alt="Screenshot 2021-05-09 at 20 24 03" src="https://user-images.githubusercontent.com/148686/117581249-8d16cf80-b104-11eb-9ab0-e35720cdb568.png">

**Comment by martinl** [comment]
Brake_Status Brake signal is not used for 2020 Crosstrek Hybrid

**Comment by martinl** [comment]
Brake_Hybrid signal for 2020 Crosstrek Hybrid (needs testing)
```
BO_ 550 Brake_Hybrid: 8 XXX
 SG_ Brake_Pedal : 24|8@1+ (1,0) [0|255] "" XXX
 SG_ Brake : 37|1@1+ (1,0) [0|1] "" XXX

```

**Comment by martinl** [comment]
Using Brake_Hybrid message fixes ACC disengage issue for 2020 Crosstrek Hybrid

**Comment by jmayes41** [comment]
> Crosstrek Hybrid 2020 (Dave32) disengage on braking issue
> 
> <img width="423" alt="Screenshot 2020-07-14 at 19 50 00" src="https://user-images.githubusercontent.com/148686/87460497-a4387e00-c615-11ea-968c-748c56517ee6.png">
> 
> 
> 
> Brake Pedal vs acceleration
> 
> <img width="416" alt="Screenshot 2020-07-14 at 21 47 17" src="https://user-images.githubusercontent.com/148686/87464377-b1f10200-c61b-11ea-8e00-b43a5a51405f.png">
> 
> 
> 
>
