### ISSUE TITLE
ACC set speed units signal

### ISSUE THREAD

**Issue by martinl** [martinl/openpilot#30]
ACC units (mph/kph) [Dash_State][Units] signal changes sometimes (eg for one day every 2-3 weeks) to a different value on Global platform models. Possible solutions are finding the reason and fix or finding more reliable ACC units signal (eg using OBD2 mode22 diagnostic query) which would also simplify current ACC units logic

Currently testing new [Dashlights][UNITS] for Global and [Dash_State2][Units] signal for preglobal models in subaru-community branch

**Comment by TK211X** [comment]
BO_ 977 Tempo_Speed_Unit: 8 XXX
 SG_ Speed_Unit_Candidate : 15|1@1+ (1,0) [0|1] "" XXX

**Comment by TK211X** [comment]
Check this. Confirmation needed.

**Comment by karlh5926** [comment]
From my drives, I can confirm this bit is correlated with Unit setting.

On my Subaru Outback 2017 2.5 UDM
0 = Metric
1 = Imperial

**Comment by martinl** [comment]
Please share cabana url where you change metric / imperial a few times in dash menu. Keep comma2 camera pointed to dash while recording

**Comment by martinl** [comment]
I can confirm from preglobal Subaru Outback 2017 2.5 UDM cabana that there is correlation between units change in dash menu and following dbc signal

```
BO_ 977 Dash_State2: 8 XXX
  SG_ Units : 15|1@1+ (1,0) [0|1] "" XXX
```

I requested more cabana urls for different preglobal models and model years to confirm before moving forward with adding the new signal to opendbc and carstate for testing

**Comment by martinl** [comment]
Here is one promising candidate for Global:
```
BO_ 912 Dashlights: 8 XXX
 SG_ Units : 24|1@1+ (1,0) [0|1] "" XXX
```
<img width="442" alt="Screenshot 2021-06-21 at 21 53 16" src="https://user-images.githubusercontent.com/148686/122813021-1eb85600-d2db-11eb-83c6-5a633ed938a1.png">

**Comment by martinl** [comment]
Dashlights UNITS signal is confirmed to have same values on 2018 Crosstrek EDM, 2020 Crosstrek UDM and 2020 Ascent UDM

**Comment by martinl** [comment]
Preglobal Dash_State2 Units signal is currently confirmed working on Subaru Outback 2017 2.5 UDM and 2019 Outback UDM

**Comment by martinl** [comment]
There have been no reports of wrong acc speed units after new signals were upstreamed, closing this for now
