### ISSUE TITLE
Add Subaru Impreza 2020 support

### ISSUE THREAD

**Issue by Trespass3r** [martinl/openpilot#36]
I own one if that helps at all. I would love to pay a $100 bounty for this to be added if possible.

**Comment by letsdudiss1** [comment]
I would take on the bounty, except it already supports Impreza 2020 unless you mean something different than "Add support"

**Comment by Trespass3r** [comment]
> I would take on the bounty, except it already supports Impreza 2020 unless you mean something different than "Add support"

https://github.com/commaai/openpilot#community-maintained-cars-and-features
>Subaru | Impreza 2017-19

**Comment by letsdudiss1** [comment]
that's not entirely accurate, just jump on discord server, you will get the help you need. I own a 2021 Impreza, and martinl's fork works with it

**Comment by Trespass3r** [comment]
> that's not entirely accurate, just jump on discord server, you will get the help you need. I own a 2021 Impreza, and martinl's fork works with it

I've been on the discord before. No one really wanted to help, but everyone was quick to make me feel stupid. Honestly it is the reason I returned the Comma Two. Felt silly spending $1200 for a tech toy I have to get made fun of to get working. If/when the 2020 Impreza is ever supported I will be buying it back. Thanks anyway.

**Comment by invictus2010** [comment]
sorry you had that experience! the impreza 2020 is supported now.
