### ISSUE TITLE
Build fail on subaru-PR-test branch

### ISSUE THREAD

**Issue by nl1031** [martinl/openpilot#45]
**Describe the bug**
Build fail on subaru-PR-test branch( 73f9 e67f 4646 0485)

**How to reproduce or log data**
root@localhost:/data/openpilot$ scons 
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd /data/openpilot/selfdrive/modeld && /data/openpilot/selfdrive/modeld/thneed/compile ../../models/supercombo.dlc ../../models/supercombo.thneed --binary
IOCTL_KGSL_DRAWCTXT_CREATE: creating context with flags 0x84201ad2
error_code=310; error_message=Dlc read failure. Failed to read archive file ; error_component=Dl Container; line_no=530; thread_id=547522080792
scons: *** [models/supercombo.thneed] Error 1
scons: building terminated because of errors.

**Expected behavior**

**Device/Version information (please complete the following information):**
 - Device: [LeEco Le Pro3 with ENOS v16.2]
 - Dongle ID: [e.g. 77611a1fac303767, can be found in Settings -> Device -> Dongle ID or my.comma.ai/useradmin]
 - Route: [e.g. 77611a1fac303767|2020-05-11--16-37-07, can be found in my.comma.ai/useradmin]
 - Timestamp: [When in the route the bug occurs (e.g. 4min 30s into the drive)]
 - Version: [subaru-PR-test branch 73f9e67f 46460485]
 - Car make/model: [Subaru legacy 2015]

**Additional context**

**Comment by martinl** [comment]
looks like incomplete git clone, remove openpilot and install again
