### ISSUE TITLE
OP steering stops working after  pressing accelerator

### ISSUE THREAD

**Issue by n0ccj** [martinl/openpilot#82]
### Describe the bug

When OP is engaged and accelerator pedal is used vehicle will never resume steering control until acc is canceled and reenabled. 

### Which car does this affect?

2021 Subaru Outback Touring XT

### Provide a route where the issue occurs

b505735ada7ab281%7C2022-08-23--14-43-21

### openpilot version

0.8.15

### Additional info

Vehicle checkbox to ignore accel pedal does not matter. Tried in both positions on and off. Light on center dic screen also goes away.

**Comment by n0ccj** [comment]
So this morning I changed to the Subaru-community release. The toggle is working, and if I toggle off the disengage op on throttle the steering stays active after release. If disengage on throttle is on it does not return to steering the vehicle after throttle release.

**Comment by martinl** [comment]
Disengage on gas press for Outback 2020-2022 is fixed since 0.8.16 when it became officially supported in upstream
