### ISSUE TITLE
SUBARU OUTBACK 2019 can't use openpilot

### ISSUE THREAD

**Issue by pizzawu** [martinl/openpilot#89]
### Describe the bug

at outback 2019 car can't use openpilot, It alway show LKAS Fault. Need restart comma.

### Which car does this affect?

subaru Outback 2019

### Provide a route where the issue occurs

google_101707854554415683966

### openpilot version

0.8.13

**Comment by martinl** [comment]
LKAS Fault usually means check usb-c and car harness connections.

**Comment by pizzawu** [comment]
only dp 0.8.13 can use. but other versions can't use. both occur LKAS  fault.
I don't think that harness has a problem.

**Comment by martinl** [comment]
which hardware and branch are you using? with C2 you should use subaru-community-c2 branch

**Comment by pizzawu** [comment]
i use comma 3 machine.
and the fork is subaru-community.

**Comment by martinl** [comment]
can you share a subaru-community route with uploaded logs where the fault happens?

**Comment by pizzawu** [comment]
too bad, When i was think change the fork, the comma3 touch panel is fault. so please wait repair,then provide the error log. sorry...

**Comment by martinl** [comment]
I'll close this issue for now since several Outback 2019 are using the branch without issues. Please open a new issue when you have a route with uploaded logs available.
