### ISSUE TITLE
Subaru Legacy 2019 Fingerprinting

### ISSUE THREAD

**Issue by invictus2010** [martinl/openpilot#92]
I performed the steps to fingerprint my 2019 Subaru Legacy. When I run it locally on C3, I still am in dashcam mode for an unsupported car.

Steps I’ve taken: 

1) grabbed the carFw values
2) updated them (https://github.com/invictus2010/openpilot/blob/subaru-community/selfdrive/car/subaru/values.py)
3) ssh'd into my C3 scp’d the above values.py file to the C3.
4) rebooted
5) still unsupported

Route name for logs: a593e22f54769614|2022-12-05--20-26-03

**Comment by martinl** [comment]
Hi

please upload logs in connect for the route and also make it public. Then I can get the carFw values from route and add the missing fw values to subaru-community

**Comment by invictus2010** [comment]
I'm officially driving chill! Thanks for the fix!

I had missed the 'Abs' value and your update corrected it. Closing the issue.
